<?php

namespace App\MessageHandler;

use App\Repository\UserRepository;
use App\Message\EmailNotification;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class EmailNotificationHandler extends AbstractController implements MessageHandlerInterface
{   
	  private $userRepo;

    function __construct(UserRepository $userRepo)
    {
    	$this->userRepo = $userRepo;
    } 

    public function __invoke(EmailNotification $message)
    {     
           $user = $this->userRepo->findOneByEmail($message->getEmail());

           $transport = (new \Swift_SmtpTransport('smtp.mailtrap.io', 2525))
               ->setUsername('6f96ac42118382') // generated by Mailtrap
               ->setPassword('2e2591ed5ce377') // generated by Mailtrap
           ;

           $mailer = new \Swift_Mailer($transport);

           if (!$user) {
             throw new \Exception("User not Found !", 1);    
           }

           $token =$user->getActivationToken();
           $message =( new \Swift_Message("Activation de compte"))
                    ->setFrom('noreplynajmi@gmail.com')
                    ->setTo($user->getEmail())
                    ->setBody(
                            $this->renderView(                   
                            'std_state/email.html.twig',
                            [
                              'user' => $user,
                              'token'=>$token
                            ]
                            )
                     , 'text/html');
            $mailer->send($message);
    }
}