<?php

namespace App\MessageHandler;

use App\Repository\UserRepository;
use App\Message\ResetPasswordEmailNotification;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;


class ResetPasswordEmailHandler  implements MessageHandlerInterface
{   
	  private $userRepo, $urlgenerator;

    function __construct(UserRepository $userRepo,
         UrlGeneratorInterface $urlgenerator)
    {
      $this->userRepo = $userRepo;
      $this->urlgenerator = $urlgenerator;
    } 

    public function __invoke(ResetPasswordEmailNotification $message)
    {
           $user = $this->userRepo->findOneByEmail($message->getEmail());

           $transport = (new \Swift_SmtpTransport('smtp.mailtrap.io', 2525))
               ->setUsername('6f96ac42118382') // generated by Mailtrap
               ->setPassword('2e2591ed5ce377') // generated by Mailtrap
           ;
           $mailer = new \Swift_Mailer($transport);
          
           
           if (!$user) {
             throw new \Exception("User not Found !", 1);    
           }
          $token = $user->getResetToken();

          $url = $this->urlgenerator->generate('app_reset_password', array('token' => $token), UrlGeneratorInterface::ABSOLUTE_URL);

        $message = (new \Swift_Message('Mot de passe oublié'))
            ->setFrom('votre@adresse.fr')
            ->setTo($user->getEmail())
            ->setBody(
                "Bonjour,<br><br>Une demande de réinitialisation de mot de passe a été effectuée pour le site Nouvelle-Techno.fr. Veuillez cliquer sur le lien suivant : <a href=" . $url.">Reset Password</a>",
                'text/html'
            )
        ;

        // On envoie l'e-mail
        $mailer->send($message);
    }
}